---
- name: Configure Redis Server
  hosts: server_role_redis_server
  become: true
  vars:
    ansible_user: rocky
  roles:
    - redis_server

- name: Configure Frontend Server
  hosts: server_role_frontend_server
  become: true
  vars:
    ansible_user: ubuntu
  roles:
    - frontend_server
